; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
SonicDynPLC_internal:	mappingsTable
		mappingsTableEntry.w	SonPLC_Null
		mappingsTableEntry.w	SonPLC_Stand
		mappingsTableEntry.w	SonPLC_Wait1
		mappingsTableEntry.w	SonPLC_Wait2
		mappingsTableEntry.w	SonPLC_Wait3
		mappingsTableEntry.w	SonPLC_LookUp1
		mappingsTableEntry.w	SonPLC_LookUp2
		mappingsTableEntry.w	SonPLC_Walk11
		mappingsTableEntry.w	SonPLC_Walk12
		mappingsTableEntry.w	SonPLC_Walk13
		mappingsTableEntry.w	SonPLC_Walk14
		mappingsTableEntry.w	SonPLC_Walk15
		mappingsTableEntry.w	SonPLC_Walk16
		mappingsTableEntry.w	SonPLC_Walk21
		mappingsTableEntry.w	SonPLC_Walk22
		mappingsTableEntry.w	SonPLC_Walk23
		mappingsTableEntry.w	SonPLC_Walk24
		mappingsTableEntry.w	SonPLC_Walk25
		mappingsTableEntry.w	SonPLC_Walk26
		mappingsTableEntry.w	SonPLC_Walk31
		mappingsTableEntry.w	SonPLC_Walk32
		mappingsTableEntry.w	SonPLC_Walk33
		mappingsTableEntry.w	SonPLC_Walk34
		mappingsTableEntry.w	SonPLC_Walk35
		mappingsTableEntry.w	SonPLC_Walk36
		mappingsTableEntry.w	SonPLC_Walk41
		mappingsTableEntry.w	SonPLC_Walk42
		mappingsTableEntry.w	SonPLC_Walk43
		mappingsTableEntry.w	SonPLC_Walk44
		mappingsTableEntry.w	SonPLC_Walk45
		mappingsTableEntry.w	SonPLC_Walk46
		mappingsTableEntry.w	SonPLC_Run11
		mappingsTableEntry.w	SonPLC_Run12
		mappingsTableEntry.w	SonPLC_Run13
		mappingsTableEntry.w	SonPLC_Run14
		mappingsTableEntry.w	SonPLC_Run21
		mappingsTableEntry.w	SonPLC_Run22
		mappingsTableEntry.w	SonPLC_Run23
		mappingsTableEntry.w	SonPLC_Run24
		mappingsTableEntry.w	SonPLC_Run31
		mappingsTableEntry.w	SonPLC_Run32
		mappingsTableEntry.w	SonPLC_Run33
		mappingsTableEntry.w	SonPLC_Run34
		mappingsTableEntry.w	SonPLC_Run41
		mappingsTableEntry.w	SonPLC_Run42
		mappingsTableEntry.w	SonPLC_Run43
		mappingsTableEntry.w	SonPLC_Run44
		mappingsTableEntry.w	SonPLC_Roll1
		mappingsTableEntry.w	SonPLC_Roll2
		mappingsTableEntry.w	SonPLC_Roll3
		mappingsTableEntry.w	SonPLC_Roll4
		mappingsTableEntry.w	SonPLC_Roll5
		mappingsTableEntry.w	SonPLC_Spindash1
		mappingsTableEntry.w	SonPLC_Spindash2
		mappingsTableEntry.w	SonPLC_Spindash3
		mappingsTableEntry.w	SonPLC_Spindash4
		mappingsTableEntry.w	SonPLC_Spindash5
		mappingsTableEntry.w	SonPLC_Spindash6
		mappingsTableEntry.w	SonPLC_Stop1
		mappingsTableEntry.w	SonPLC_Stop2
		mappingsTableEntry.w	SonPLC_Duck1
		mappingsTableEntry.w	SonPLC_Duck2
		mappingsTableEntry.w	SonPLC_Balance1
		mappingsTableEntry.w	SonPLC_Balance2
		mappingsTableEntry.w	SonPLC_BalanceForward1
		mappingsTableEntry.w	SonPLC_BalanceForward2
		mappingsTableEntry.w	SonPLC_BalanceForward3
		mappingsTableEntry.w	SonPLC_BalanceForward4
		mappingsTableEntry.w	SonPLC_BalanceBack1
		mappingsTableEntry.w	SonPLC_BalanceBack2
		mappingsTableEntry.w	SonPLC_BalanceBack3
		mappingsTableEntry.w	SonPLC_BalanceBack4
		mappingsTableEntry.w	SonPLC_Float1
		mappingsTableEntry.w	SonPLC_Float2
		mappingsTableEntry.w	SonPLC_Float3
		mappingsTableEntry.w	SonPLC_Float4
		mappingsTableEntry.w	SonPLC_Float1
		mappingsTableEntry.w	SonPLC_Float3
		mappingsTableEntry.w	SonPLC_Spring
		mappingsTableEntry.w	SonPLC_Hang1
		mappingsTableEntry.w	SonPLC_Hang2
		mappingsTableEntry.w	SonPLC_Push1
		mappingsTableEntry.w	SonPLC_Push2
		mappingsTableEntry.w	SonPLC_Push3
		mappingsTableEntry.w	SonPLC_Push4
		mappingsTableEntry.w	SonPLC_BubStand
		mappingsTableEntry.w	SonPLC_Death
		mappingsTableEntry.w	SonPLC_Drown
		mappingsTableEntry.w	SonPLC_Shrink1
		mappingsTableEntry.w	SonPLC_Shrink2
		mappingsTableEntry.w	SonPLC_Shrink3
		mappingsTableEntry.w	SonPLC_Shrink4
		mappingsTableEntry.w	SonPLC_Shrink5
		mappingsTableEntry.w	SonPLC_Hurt
		mappingsTableEntry.w	SonPLC_GetAir
		mappingsTableEntry.w	SonPLC_WaterSlide
		mappingsTableEntry.w	SonPLC_Dash11
		mappingsTableEntry.w	SonPLC_Dash12
		mappingsTableEntry.w	SonPLC_Dash13
		mappingsTableEntry.w	SonPLC_Dash14
		mappingsTableEntry.w	SonPLC_Dash21
		mappingsTableEntry.w	SonPLC_Dash22
		mappingsTableEntry.w	SonPLC_Dash23
		mappingsTableEntry.w	SonPLC_Dash24
		mappingsTableEntry.w	SonPLC_Dash31
		mappingsTableEntry.w	SonPLC_Dash32
		mappingsTableEntry.w	SonPLC_Dash33
		mappingsTableEntry.w	SonPLC_Dash34
		mappingsTableEntry.w	SonPLC_Dash41
		mappingsTableEntry.w	SonPLC_Dash42
		mappingsTableEntry.w	SonPLC_Dash43
		mappingsTableEntry.w	SonPLC_Dash44
		mappingsTableEntry.w	SonPLC_Transform1
		mappingsTableEntry.w	SonPLC_Transform2
		mappingsTableEntry.w	SonPLC_Transform3
		mappingsTableEntry.w	SonPLC_Transform4
		mappingsTableEntry.w	SonPLC_Transform5

SonPLC_Null:	dplcHeader
SonPLC_Null_End

SonPLC_Stand:	dplcHeader
	dplcEntry	$10, 0
	dplcEntry	1, $10
SonPLC_Stand_End

SonPLC_Wait1:	dplcHeader
	dplcEntry	$F, $11
SonPLC_Wait1_End

SonPLC_Wait2:	dplcHeader
	dplcEntry	6, $20
	dplcEntry	9, $17
SonPLC_Wait2_End

SonPLC_Wait3:	dplcHeader
	dplcEntry	6, $20
	dplcEntry	6, $17
	dplcEntry	3, $26
SonPLC_Wait3_End

SonPLC_LookUp1:	dplcHeader
	dplcEntry	$D, $668
	dplcEntry	3, $E
SonPLC_LookUp1_End

SonPLC_LookUp2:	dplcHeader
	dplcEntry	9, $29
	dplcEntry	6, $B
SonPLC_LookUp2_End

SonPLC_Walk11:	dplcHeader
	dplcEntry	$10, $32
	dplcEntry	6, $42
SonPLC_Walk11_End

SonPLC_Walk12:	dplcHeader
	dplcEntry	8, $32
	dplcEntry	$C, $48
SonPLC_Walk12_End

SonPLC_Walk13:	dplcHeader
	dplcEntry	$F, $54
SonPLC_Walk13_End

SonPLC_Walk14:	dplcHeader
	dplcEntry	6, $54
	dplcEntry	$E, $63
SonPLC_Walk14_End

SonPLC_Walk15:	dplcHeader
	dplcEntry	6, $54
	dplcEntry	$C, $71
SonPLC_Walk15_End

SonPLC_Walk16:	dplcHeader
	dplcEntry	8, $32
	dplcEntry	$A, $7D
SonPLC_Walk16_End

SonPLC_Walk21:	dplcHeader
	dplcEntry	$10, $87
	dplcEntry	6, $97
SonPLC_Walk21_End

SonPLC_Walk22:	dplcHeader
	dplcEntry	6, $87
	dplcEntry	$10, $9D
	dplcEntry	1, $AD
SonPLC_Walk22_End

SonPLC_Walk23:	dplcHeader
	dplcEntry	$10, $AE
	dplcEntry	3, $BE
SonPLC_Walk23_End

SonPLC_Walk24:	dplcHeader
	dplcEntry	$10, $C1
	dplcEntry	7, $D1
SonPLC_Walk24_End

SonPLC_Walk25:	dplcHeader
	dplcEntry	6, $C1
	dplcEntry	$D, $D8
SonPLC_Walk25_End

SonPLC_Walk26:	dplcHeader
	dplcEntry	6, $87
	dplcEntry	2, $9D
	dplcEntry	1, $93
	dplcEntry	$B, $E5
SonPLC_Walk26_End

SonPLC_Walk31:	dplcHeader
	dplcEntry	$10, $F0
	dplcEntry	6, $100
SonPLC_Walk31_End

SonPLC_Walk32:	dplcHeader
	dplcEntry	8, $F0
	dplcEntry	$C, $106
SonPLC_Walk32_End

SonPLC_Walk33:	dplcHeader
	dplcEntry	$F, $112
SonPLC_Walk33_End

SonPLC_Walk34:	dplcHeader
	dplcEntry	6, $112
	dplcEntry	$E, $121
SonPLC_Walk34_End

SonPLC_Walk35:	dplcHeader
	dplcEntry	6, $112
	dplcEntry	$C, $12F
SonPLC_Walk35_End

SonPLC_Walk36:	dplcHeader
	dplcEntry	8, $F0
	dplcEntry	1, $106
	dplcEntry	9, $13B
SonPLC_Walk36_End

SonPLC_Walk41:	dplcHeader
	dplcEntry	$10, $144
	dplcEntry	5, $154
SonPLC_Walk41_End

SonPLC_Walk42:	dplcHeader
	dplcEntry	6, $144
	dplcEntry	$10, $159
	dplcEntry	1, $157
SonPLC_Walk42_End

SonPLC_Walk43:	dplcHeader
	dplcEntry	$10, $169
	dplcEntry	3, $179
SonPLC_Walk43_End

SonPLC_Walk44:	dplcHeader
	dplcEntry	6, $17C
	dplcEntry	$10, $182
SonPLC_Walk44_End

SonPLC_Walk45:	dplcHeader
	dplcEntry	6, $17C
	dplcEntry	$D, $192
SonPLC_Walk45_End

SonPLC_Walk46:	dplcHeader
	dplcEntry	6, $144
	dplcEntry	9, $19F
	dplcEntry	2, $15E
	dplcEntry	2, $1A8
	dplcEntry	1, $157
SonPLC_Walk46_End

SonPLC_Run11:	dplcHeader
	dplcEntry	6, $1AA
	dplcEntry	$C, $1B0
SonPLC_Run11_End

SonPLC_Run12:	dplcHeader
	dplcEntry	6, $54
	dplcEntry	$C, $1BC
SonPLC_Run12_End

SonPLC_Run13:	dplcHeader
	dplcEntry	6, $1AA
	dplcEntry	$C, $1C8
SonPLC_Run13_End

SonPLC_Run14:	dplcHeader
	dplcEntry	6, $54
	dplcEntry	$C, $1D4
SonPLC_Run14_End

SonPLC_Run21:	dplcHeader
	dplcEntry	6, $1E0
	dplcEntry	2, $1E6
	dplcEntry	$C, $1E8
	dplcEntry	1, $1F4
SonPLC_Run21_End

SonPLC_Run22:	dplcHeader
	dplcEntry	6, $1F5
	dplcEntry	2, $1FB
	dplcEntry	$C, $1FD
SonPLC_Run22_End

SonPLC_Run23:	dplcHeader
	dplcEntry	6, $1E0
	dplcEntry	2, $209
	dplcEntry	$C, $20B
	dplcEntry	1, $1F4
SonPLC_Run23_End

SonPLC_Run24:	dplcHeader
	dplcEntry	6, $1F5
	dplcEntry	2, $1FB
	dplcEntry	$C, $217
SonPLC_Run24_End

SonPLC_Run31:	dplcHeader
	dplcEntry	6, $223
	dplcEntry	$C, $229
SonPLC_Run31_End

SonPLC_Run32:	dplcHeader
	dplcEntry	6, $112
	dplcEntry	$C, $235
SonPLC_Run32_End

SonPLC_Run33:	dplcHeader
	dplcEntry	6, $223
	dplcEntry	$C, $241
SonPLC_Run33_End

SonPLC_Run34:	dplcHeader
	dplcEntry	6, $112
	dplcEntry	$C, $24D
SonPLC_Run34_End

SonPLC_Run41:	dplcHeader
	dplcEntry	6, $259
	dplcEntry	2, $25F
	dplcEntry	$C, $261
	dplcEntry	1, $26D
SonPLC_Run41_End

SonPLC_Run42:	dplcHeader
	dplcEntry	8, $26E
	dplcEntry	$C, $276
SonPLC_Run42_End

SonPLC_Run43:	dplcHeader
	dplcEntry	6, $259
	dplcEntry	2, $282
	dplcEntry	$C, $284
	dplcEntry	1, $26D
SonPLC_Run43_End

SonPLC_Run44:	dplcHeader
	dplcEntry	8, $26E
	dplcEntry	$C, $290
SonPLC_Run44_End

SonPLC_Roll1:	dplcHeader
	dplcEntry	$10, $29C
SonPLC_Roll1_End

SonPLC_Roll2:	dplcHeader
	dplcEntry	$10, $2AC
SonPLC_Roll2_End

SonPLC_Roll3:	dplcHeader
	dplcEntry	$10, $2BC
SonPLC_Roll3_End

SonPLC_Roll4:	dplcHeader
	dplcEntry	$10, $2CC
SonPLC_Roll4_End

SonPLC_Roll5:	dplcHeader
	dplcEntry	$10, $2DC
SonPLC_Roll5_End

SonPLC_Spindash1:	dplcHeader
	dplcEntry	$10, $4C2
SonPLC_Spindash1_End

SonPLC_Spindash2:	dplcHeader
	dplcEntry	$10, $4D2
SonPLC_Spindash2_End

SonPLC_Spindash3:	dplcHeader
	dplcEntry	$10, $4E2
SonPLC_Spindash3_End

SonPLC_Spindash4:	dplcHeader
	dplcEntry	$10, $4F2
SonPLC_Spindash4_End

SonPLC_Spindash5:	dplcHeader
	dplcEntry	$10, $502
SonPLC_Spindash5_End

SonPLC_Spindash6:	dplcHeader
	dplcEntry	$10, $512
SonPLC_Spindash6_End

SonPLC_Stop1:	dplcHeader
	dplcEntry	6, $32A
	dplcEntry	$C, $330
SonPLC_Stop1_End

SonPLC_Stop2:	dplcHeader
	dplcEntry	6, $33C
	dplcEntry	8, $342
	dplcEntry	2, $34A
	dplcEntry	1, $34C
SonPLC_Stop2_End

SonPLC_Duck1:	dplcHeader
	dplcEntry	9, $675
	dplcEntry	3, $E
SonPLC_Duck1_End

SonPLC_Duck2:	dplcHeader
	dplcEntry	2, $34D
	dplcEntry	8, $34F
	dplcEntry	3, $357
	dplcEntry	1, $35A
SonPLC_Duck2_End

SonPLC_Balance1:	dplcHeader
	dplcEntry	3, $35B
	dplcEntry	3, $35E
	dplcEntry	$10, $361
SonPLC_Balance1_End

SonPLC_Balance2:	dplcHeader
	dplcEntry	$C, $371
	dplcEntry	8, $37D
	dplcEntry	1, $71
SonPLC_Balance2_End

SonPLC_BalanceForward1:	dplcHeader
	dplcEntry	4, $6CE
	dplcEntry	$10, $6D2
SonPLC_BalanceForward1_End

SonPLC_BalanceForward2:	dplcHeader
	dplcEntry	3, $6CE
	dplcEntry	$10, $6E2
	dplcEntry	3, $6F2
SonPLC_BalanceForward2_End

SonPLC_BalanceForward3:	dplcHeader
	dplcEntry	$10, $6F5
	dplcEntry	4, $705
SonPLC_BalanceForward3_End

SonPLC_BalanceForward4:	dplcHeader
	dplcEntry	$10, $709
	dplcEntry	4, $719
SonPLC_BalanceForward4_End

SonPLC_BalanceBack1:	dplcHeader
	dplcEntry	$10, $67E
	dplcEntry	5, $68E
SonPLC_BalanceBack1_End

SonPLC_BalanceBack2:	dplcHeader
	dplcEntry	$10, $693
	dplcEntry	3, $6A3
SonPLC_BalanceBack2_End

SonPLC_BalanceBack3:	dplcHeader
	dplcEntry	$10, $6A6
	dplcEntry	7, $69F
SonPLC_BalanceBack3_End

SonPLC_BalanceBack4:	dplcHeader
	dplcEntry	$10, $6B6
	dplcEntry	4, $6C6
SonPLC_BalanceBack4_End

SonPLC_Float1:	dplcHeader
	dplcEntry	$F, $385
SonPLC_Float1_End

SonPLC_Float2:	dplcHeader
	dplcEntry	9, $394
SonPLC_Float2_End

SonPLC_Float3:	dplcHeader
	dplcEntry	$D, $39D
SonPLC_Float3_End

SonPLC_Float4:	dplcHeader
	dplcEntry	$F, $3AA
SonPLC_Float4_End

SonPLC_Spring:	dplcHeader
	dplcEntry	$F, $3B9
SonPLC_Spring_End

; ======================================
; DPLC Entry optimization left off here
; ======================================

SonPLC_Hang1:	dplcHeader
	dplcEntry	$C, $3C8
	dplcEntry	4, $3D4
	dplcEntry	1, $3D8
	dplcEntry	1, $3D9
SonPLC_Hang1_End

SonPLC_Hang2:	dplcHeader
	dplcEntry	$C, $3DA
	dplcEntry	4, $3E6
	dplcEntry	1, $3EA
	dplcEntry	1, $3EB
SonPLC_Hang2_End

SonPLC_Push1:	dplcHeader
	dplcEntry	9, $3EC
	dplcEntry	8, $3F5
SonPLC_Push1_End

SonPLC_Push2:	dplcHeader
	dplcEntry	9, $3FD
	dplcEntry	3, $406
	dplcEntry	2, $409
SonPLC_Push2_End

SonPLC_Push3:	dplcHeader
	dplcEntry	9, $40B
	dplcEntry	8, $414
SonPLC_Push3_End

SonPLC_Push4:	dplcHeader
	dplcEntry	9, $3FD
	dplcEntry	3, $41C
	dplcEntry	2, $41F
SonPLC_Push4_End

SonPLC_BubStand:	dplcHeader
	dplcEntry	$E, $421
SonPLC_BubStand_End

; =====================================================================
; Tiles start at $42F
; =====================================================================

SonPLC_Death:	dplcHeader
	dplcEntry	8, $444
	dplcEntry	2, $437
	dplcEntry	6, $44C
	dplcEntry	5, $43F
SonPLC_Death_End

SonPLC_Drown:	dplcHeader
	dplcEntry	$10, $42F
	dplcEntry	5, $43F
SonPLC_Drown_End

SonPLC_Shrink1:	dplcHeader
	dplcEntry	3, $452
	dplcEntry	$10, $455
SonPLC_Shrink1_End

SonPLC_Shrink2:	dplcHeader
	dplcEntry	$10, $465
	dplcEntry	2, $475
SonPLC_Shrink2_End

SonPLC_Shrink3:	dplcHeader
	dplcEntry	$C, $477
SonPLC_Shrink3_End

SonPLC_Shrink4:	dplcHeader
	dplcEntry	6, $483
SonPLC_Shrink4_End

SonPLC_Shrink5:	dplcHeader
	dplcEntry	2, $489
SonPLC_Shrink5_End

SonPLC_Hurt:	dplcHeader
	dplcEntry	$10, $48B
	dplcEntry	2, $49B
SonPLC_Hurt_End

SonPLC_GetAir:	dplcHeader
	dplcEntry	6, $49D
	dplcEntry	$C, $4A3
	dplcEntry	2, $6D
SonPLC_GetAir_End

SonPLC_WaterSlide:	dplcHeader
	dplcEntry	$10, $4AF
	dplcEntry	3, $4BF
SonPLC_WaterSlide_End

SonPLC_Dash11:	dplcHeader
	dplcEntry	3, $522
	dplcEntry	$10, $525
SonPLC_Dash11_End

SonPLC_Dash12:	dplcHeader
	dplcEntry	3, $535
	dplcEntry	$10, $538
SonPLC_Dash12_End

SonPLC_Dash13:	dplcHeader
	dplcEntry	3, $548
	dplcEntry	$10, $54B
SonPLC_Dash13_End

SonPLC_Dash14:	dplcHeader
	dplcEntry	2, $55B
	dplcEntry	$10, $55D
SonPLC_Dash14_End

SonPLC_Dash21:	dplcHeader
	dplcEntry	$10, $56D
	dplcEntry	7, $57D
SonPLC_Dash21_End

SonPLC_Dash22:	dplcHeader
	dplcEntry	$10, $584
	dplcEntry	5, $594
SonPLC_Dash22_End

SonPLC_Dash23:	dplcHeader
	dplcEntry	$10, $599
	dplcEntry	7, $5A9
SonPLC_Dash23_End

SonPLC_Dash24:	dplcHeader
	dplcEntry	$10, $5B0
	dplcEntry	5, $5C0
SonPLC_Dash24_End

SonPLC_Dash31:	dplcHeader
	dplcEntry	$10, $5C5
	dplcEntry	3, $5D5
SonPLC_Dash31_End

SonPLC_Dash32:	dplcHeader
	dplcEntry	$10, $5D8
	dplcEntry	3, $5E8
SonPLC_Dash32_End

SonPLC_Dash33:	dplcHeader
	dplcEntry	$10, $5EB
	dplcEntry	3, $5FB
SonPLC_Dash33_End

SonPLC_Dash34:	dplcHeader
	dplcEntry	$10, $5FE
	dplcEntry	2, $60E
SonPLC_Dash34_End

SonPLC_Dash41:	dplcHeader
	dplcEntry	$10, $610
	dplcEntry	7, $620
SonPLC_Dash41_End

SonPLC_Dash42:	dplcHeader
	dplcEntry	$10, $627
	dplcEntry	5, $637
SonPLC_Dash42_End

SonPLC_Dash43:	dplcHeader
	dplcEntry	$10, $63C
	dplcEntry	7, $64C
SonPLC_Dash43_End

SonPLC_Dash44:	dplcHeader
	dplcEntry	$10, $653
	dplcEntry	5, $663
SonPLC_Dash44_End

SonPLC_Transform1:	dplcHeader
	dplcEntry	$C, $71E
SonPLC_Transform1_End

SonPLC_Transform2:	dplcHeader
	dplcEntry	$C, $72A
	dplcEntry	$2, $736
	dplcEntry	$6, $738
SonPLC_Transform2_End

SonPLC_Transform3:	dplcHeader
	dplcEntry	9, $73E
	dplcEntry	1, $769
	dplcEntry	9, $748
SonPLC_Transform3_End

SonPLC_Transform4:	dplcHeader
	dplcEntry	3, $751
	dplcEntry	2, $754
	dplcEntry	4, $756
	dplcEntry	9, $75A
	dplcEntry	1, $763
SonPLC_Transform4_End

SonPLC_Transform5:	dplcHeader
	dplcEntry	3, $764
	dplcEntry	2, $767
	dplcEntry	4, $756
	dplcEntry	9, $75A
	dplcEntry	1, $763
SonPLC_Transform5_End
	even