; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
DynPLC_Effects:	mappingsTable
		mappingsTableEntry.w	.null
		mappingsTableEntry.w	.spindash1
		mappingsTableEntry.w	.spindash2
		mappingsTableEntry.w	.spindash3
		mappingsTableEntry.w	.spindash4
		mappingsTableEntry.w	.spindash5
		mappingsTableEntry.w	.spindash6
		mappingsTableEntry.w	.spindash7
		mappingsTableEntry.w	.skid
		mappingsTableEntry.w	.skid
		mappingsTableEntry.w	.skid
		mappingsTableEntry.w	.skid

.null:	dplcHeader
.null_End

.spindash1:	dplcHeader
	dplcEntry	8, 0
.spindash1_End

.spindash2:	dplcHeader
	dplcEntry	8, 8
.spindash2_End

.spindash3:	dplcHeader
	dplcEntry	8, $10
.spindash3_End

.spindash4:	dplcHeader
	dplcEntry	2, $18
	dplcEntry	8, $1A
.spindash4_End

.spindash5:	dplcHeader
	dplcEntry	4, $22
	dplcEntry	8, $26
.spindash5_End

.spindash6:	dplcHeader
	dplcEntry	6, $2E
	dplcEntry	8, $34
.spindash6_End

.spindash7:	dplcHeader
	dplcEntry	6, $3C
	dplcEntry	8, $42
.spindash7_End

.skid:	dplcHeader
	dplcEntry	$10, $4A
.skid_End
	even
