; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_Effects:	mappingsTable
	mappingsTableEntry.w	.null
	mappingsTableEntry.w	.spindash1
	mappingsTableEntry.w	.spindash1
	mappingsTableEntry.w	.spindash1
	mappingsTableEntry.w	.spindash2
	mappingsTableEntry.w	.spindash3
	mappingsTableEntry.w	.spindash4
	mappingsTableEntry.w	.spindash4
	mappingsTableEntry.w	.skid1
	mappingsTableEntry.w	.skid2
	mappingsTableEntry.w	.skid3
	mappingsTableEntry.w	.skid4
	mappingsTableEntry.w	.dropdash1
	mappingsTableEntry.w	.dropdash2
	mappingsTableEntry.w	.dropdash3
	mappingsTableEntry.w	.dropdash4
	mappingsTableEntry.w	.dropdash5
	mappingsTableEntry.w	.dropdash6
	mappingsTableEntry.w	.dropdash7
	mappingsTableEntry.w	.dropdash8

.null:	spriteHeader
.null_End

.spindash1:	spriteHeader
	spritePiece	-$20, 4, 4, 2, 0, 0, 0, 0, 0
.spindash1_End

.spindash2:	spriteHeader
	spritePiece	-$18, -$C, 1, 2, 0, 0, 0, 0, 0
	spritePiece	-$20, 4, 4, 2, 2, 0, 0, 0, 0
.spindash2_End

.spindash3:	spriteHeader
	spritePiece	-$18, -$C, 2, 2, 0, 0, 0, 0, 0
	spritePiece	-$20, 4, 4, 2, 4, 0, 0, 0, 0
.spindash3_End

.spindash4:	spriteHeader
	spritePiece	-$20, -$C, 3, 2, 0, 0, 0, 0, 0
	spritePiece	-$20, 4, 4, 2, 6, 0, 0, 0, 0
.spindash4_End

.skid1:	spriteHeader
	spritePiece	-8, -8, 2, 2, 0, 0, 0, 0, 0
.skid1_End

.skid2:	spriteHeader
	spritePiece	-8, -8, 2, 2, 4, 0, 0, 0, 0
.skid2_End

.skid3:	spriteHeader
	spritePiece	-8, -8, 2, 2, 8, 0, 0, 0, 0
.skid3_End

.skid4:	spriteHeader
	spritePiece	-8, -8, 2, 2, $C, 0, 0, 0, 0
.skid4_End

.dropdash1:	spriteHeader
 spritePiece -$18, -4, 3, 2, 0, 0, 0, 0, 0
.dropdash1_End

.dropdash2:	spriteHeader
 spritePiece -$18, -4, 3, 2, 0, 0, 0, 0, 0			; 6
.dropdash2_End

.dropdash3:	spriteHeader
 spritePiece -$18, -$C, 3, 3, 0, 0, 0, 0, 0		; C
.dropdash3_End

.dropdash4:	spriteHeader
 spritePiece -$18, -$C, 3, 3, 0, 0, 0, 0, 0		; $15
.dropdash4_End

.dropdash5:	spriteHeader
 spritePiece -$18, -$C, 3, 3, 0, 0, 0, 0, 0		; $1E
.dropdash5_End

.dropdash6:	spriteHeader
 spritePiece -$18, -$C, 3, 3, 0, 0, 0, 0, 0		; $27
.dropdash6_End

.dropdash7:	spriteHeader
 spritePiece -$18, -$C, 4, 3, 0, 0, 0, 0, 0		; $30
.dropdash7_End

.dropdash8:	spriteHeader
 spritePiece -$18, -$C, 3, 3, 0, 0, 0, 0, 0		; $3C
.dropdash8_End
	
        even

