; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------

; RetroKoH VRAM Overhaul

Map_GRing:	mappingsTable
	mappingsTableEntry.w	GRing_0 ; O
	mappingsTableEntry.w	GRing_1 ; first rotation
	mappingsTableEntry.w	GRing_2 ; second rotation (OLD first rotation)
	mappingsTableEntry.w	GRing_3 ; third rotation
	mappingsTableEntry.w	GRing_4 ; side
	mappingsTableEntry.w	GRing_5 ; third rotation REVERSE
	mappingsTableEntry.w	GRing_6 ; second rotation REVERSE
	mappingsTableEntry.w	GRing_7 ; first rotation REVERSE
	mappingsTableEntry.w	GFlash_0
	mappingsTableEntry.w	GFlash_1
	mappingsTableEntry.w	GFlash_2
	mappingsTableEntry.w	GFlash_3
	mappingsTableEntry.w	GFlash_4
	mappingsTableEntry.w	GFlash_5
	mappingsTableEntry.w	GFlash_6
	mappingsTableEntry.w	GFlash_7

GRing_0:	spriteHeader
	spritePiece	-$20, -$20, 4, 2, 0, 0, 0, 0, 0
	spritePiece	0, -$20, 4, 2, 8, 0, 0, 0, 0
	spritePiece	-$20, -$10, 2, 4, $10, 0, 0, 0, 0
	spritePiece	$10, -$10, 2, 4, $18, 0, 0, 0, 0
	spritePiece	-$20, $10, 4, 2, $20, 0, 0, 0, 0
	spritePiece	0, $10, 4, 2, $28, 0, 0, 0, 0
GRing_0_End

GRing_1:	spriteHeader
	spritePiece	-$18, -$20, 3, 2, 0, 0, 0, 0, 0
	spritePiece	0, -$20, 3, 2, 6, 0, 0, 0, 0
	spritePiece	-$20, -$10, 3, 1, $C, 0, 0, 0, 0
	spritePiece	8, -$10, 3, 1, $F, 0, 0, 0, 0
	spritePiece	-$20, -8, 2, 2, $12, 0, 0, 0, 0
	spritePiece	8, -8, 3, 2, $16, 0, 0, 0, 0
	spritePiece	-$20, 8, 3, 1, $1C, 0, 0, 0, 0
	spritePiece	8, 8, 3, 1, $1F, 0, 0, 0, 0
	spritePiece	-$18, $10, 3, 2, $22, 0, 0, 0, 0
	spritePiece	0, $10, 3, 2, $28, 0, 0, 0, 0
GRing_1_End

GRing_2:	spriteHeader
	spritePiece	-$10, -$20, 4, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, -$18, 3, 1, 4, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 2, 7, 0, 0, 0, 0
	spritePiece	-$18, -$10, 2, 4, $D, 0, 0, 0, 0
	spritePiece	8, -8, 2, 2, $15, 0, 0, 0, 0
	spritePiece	0, 8, 3, 2, $19, 0, 0, 0, 0
	spritePiece	-$18, $10, 3, 1, $1F, 0, 0, 0, 0
	spritePiece	-$10, $18, 4, 1, $22, 0, 0, 0, 0
GRing_2_End

GRing_3:	spriteHeader
	spritePiece	-$10, -$20, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 4, $10, 0, 0, 0, 0
GRing_3_End

GRing_4:	spriteHeader
	spritePiece	-$C, -$20, 2, 4, 0, 0, 0, 0, 0
	spritePiece	4, -$20, 1, 4, 0, 1, 0, 0, 0
	spritePiece	-$C, 0, 2, 4, 8, 0, 0, 0, 0
	spritePiece	4, 0, 1, 4, 8, 1, 0, 0, 0
GRing_4_End

GRing_5:	spriteHeader
	spritePiece	-$10, -$20, 4, 4, 0, 1, 0, 0, 0
	spritePiece	-$10, 0, 4, 4, $10, 1, 0, 0, 0
GRing_5_End

GRing_6:	spriteHeader
	spritePiece	-$10, -$20, 4, 1, 0, 1, 0, 0, 0
	spritePiece	0, -$18, 3, 1, 4, 1, 0, 0, 0
	spritePiece	-$18, -$18, 3, 2, 7, 1, 0, 0, 0
	spritePiece	8, -$10, 2, 4, $D, 1, 0, 0, 0
	spritePiece	-$18, -8, 2, 2, $15, 1, 0, 0, 0
	spritePiece	-$18, 8, 3, 2, $19, 1, 0, 0, 0
	spritePiece	0, $10, 3, 1, $1F, 1, 0, 0, 0
	spritePiece	-$10, $18, 4, 1, $22, 1, 0, 0, 0
GRing_6_End

GRing_7:	spriteHeader
	spritePiece	0, -$20, 3, 2, 0, 1, 0, 0, 0
	spritePiece	-$18, -$20, 3, 2, 6, 1, 0, 0, 0
	spritePiece	8, -$10, 3, 1, $C, 1, 0, 0, 0
	spritePiece	-$20, -$10, 3, 1, $F, 1, 0, 0, 0
	spritePiece	$10, -8, 2, 2, $12, 1, 0, 0, 0
	spritePiece	-$20, -8, 3, 2, $16, 1, 0, 0, 0
	spritePiece	8, 8, 3, 1, $1C, 1, 0, 0, 0
	spritePiece	-$20, 8, 3, 1, $1F, 1, 0, 0, 0
	spritePiece	0, $10, 3, 2, $22, 1, 0, 0, 0
	spritePiece	-$18, $10, 3, 2, $28, 1, 0, 0, 0
GRing_7_End

GFlash_0:	spriteHeader
	spritePiece	0, -$20, 4, 4, 0, 0, 0, 0, 0		; Tile Offset $BA
	spritePiece	0, 0, 4, 4, 0, 0, 1, 0, 0
GFlash_0_End

GFlash_1:	spriteHeader
	spritePiece	-$10, -$20, 4, 4, 0, 0, 0, 0, 0	; Tile Offset $CA
	spritePiece	$10, -$20, 2, 4, $10, 0, 0, 0, 0
	spritePiece	-$10, 0, 4, 4, 0, 0, 1, 0, 0
	spritePiece	$10, 0, 2, 4, $10, 0, 1, 0, 0
GFlash_1_End

GFlash_2:	spriteHeader
	spritePiece	-$18, -$20, 4, 4, 0, 0, 0, 0, 0	; Tile Offset $E2
	spritePiece	8, -$20, 3, 4, $10, 0, 0, 0, 0	; Tile Offset $F2
	spritePiece	-$18, 0, 4, 4, 0, 0, 1, 0, 0	; Tile Offset $E2
	spritePiece	8, 0, 3, 4, $10, 0, 1, 0, 0		; Tile Offset $FA
GFlash_2_End

GFlash_3:	spriteHeader
	spritePiece	-$20, -$20, 4, 4, 0, 1, 0, 0, 0	; Tile Offset $EE
	spritePiece	0, -$20, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-$20, 0, 4, 4, 0, 1, 1, 0, 0
	spritePiece	0, 0, 4, 4, 0, 0, 1, 0, 0
GFlash_3_End

GFlash_4:	spriteHeader
	spritePiece	-$20, -$20, 3, 4, $10, 1, 0, 0, 0	; Tile Offset $E2
	spritePiece	-8, -$20, 4, 4, 0, 1, 0, 0, 0
	spritePiece	-$20, 0, 3, 4, $10, 1, 1, 0, 0
	spritePiece	-8, 0, 4, 4, 0, 1, 1, 0, 0
GFlash_4_End

GFlash_5:	spriteHeader
	spritePiece	-$20, -$20, 2, 4, $10, 1, 0, 0, 0	; Tile Offset $CA
	spritePiece	-$10, -$20, 4, 4, 0, 1, 0, 0, 0
	spritePiece	-$20, 0, 2, 4, $10, 1, 1, 0, 0
	spritePiece	-$10, 0, 4, 4, 0, 1, 1, 0, 0
GFlash_5_End

GFlash_6:	spriteHeader
	spritePiece	-$20, -$20, 4, 4, 0, 1, 0, 0, 0		; Tile Offset $BA
	spritePiece	-$20, 0, 4, 4, 0, 1, 1, 0, 0
GFlash_6_End

GFlash_7:	spriteHeader
	spritePiece	-$20, -$20, 4, 4, 0, 0, 0, 0, 0	; Tile Offset $FE
	spritePiece	0, -$20, 4, 4, 0, 1, 0, 0, 0
	spritePiece	-$20, 0, 4, 4, 0, 0, 1, 0, 0
	spritePiece	0, 0, 4, 4, 0, 1, 1, 0, 0
GFlash_7_End

	even