; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_FlameShield:	mappingsTable
	mappingsTableEntry.w	Shield_F_0
	mappingsTableEntry.w	Shield_F_1
	mappingsTableEntry.w	Shield_F_2
	mappingsTableEntry.w	Shield_F_3
	mappingsTableEntry.w	Shield_F_4
	mappingsTableEntry.w	Shield_F_5
	mappingsTableEntry.w	Shield_F_6
	mappingsTableEntry.w	Shield_F_7
	mappingsTableEntry.w	Shield_F_8
	mappingsTableEntry.w	Shield_F_9
	mappingsTableEntry.w	Shield_F_A
	mappingsTableEntry.w	Shield_F_B
	mappingsTableEntry.w	Shield_F_C
	mappingsTableEntry.w	Shield_F_D
	mappingsTableEntry.w	Shield_F_E
	mappingsTableEntry.w	Shield_F_F
	mappingsTableEntry.w	Shield_F_10
	mappingsTableEntry.w	Shield_F_11
	mappingsTableEntry.w	Shield_F_12
	mappingsTableEntry.w	Shield_F_13
	mappingsTableEntry.w	Shield_F_14
	mappingsTableEntry.w	Shield_F_15
	mappingsTableEntry.w	Shield_F_16
	mappingsTableEntry.w	Shield_F_17
	mappingsTableEntry.w	Shield_F_18

Shield_F_0:	spriteHeader
	spritePiece	-$10, 8, 1, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, $10, 3, 1, 1, 0, 0, 0, 0
	spritePiece	0, 8, 3, 2, 4, 0, 0, 0, 0
Shield_F_0_End

Shield_F_1:	spriteHeader
	spritePiece	-$10, 0, 2, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, 8, 3, 2, 2, 0, 0, 0, 0
	spritePiece	0, 8, 3, 2, 8, 0, 0, 0, 0
Shield_F_1_End

Shield_F_2:	spriteHeader
	spritePiece	-8, -8, 1, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 1, 0, 0, 0, 0
	spritePiece	0, 0, 3, 3, $A, 0, 0, 0, 0
Shield_F_2_End

Shield_F_3:	spriteHeader
	spritePiece	-$10, -$10, 3, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, -8, 3, 3, 3, 0, 0, 0, 0
	spritePiece	0, -8, 3, 3, $C, 0, 0, 0, 0
Shield_F_3_End

Shield_F_4:	spriteHeader
	spritePiece	-$18, -$10, 3, 2, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 3, 2, 6, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 2, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 2, 6, 0, 1, 0, 0
Shield_F_4_End

Shield_F_5:	spriteHeader
	spritePiece	-8, 8, 3, 1, 0, 1, 1, 0, 0
	spritePiece	0, -$10, 3, 3, 3, 1, 1, 0, 0
	spritePiece	-$18, -$10, 3, 3, $C, 1, 1, 0, 0
Shield_F_5_End

Shield_F_6:	spriteHeader
	spritePiece	0, 0, 1, 1, 0, 1, 1, 0, 0
	spritePiece	0, -$18, 3, 3, 1, 1, 1, 0, 0
	spritePiece	-$18, -$18, 3, 3, $A, 1, 1, 0, 0
Shield_F_6_End

Shield_F_7:	spriteHeader
	spritePiece	0, -8, 2, 1, 0, 1, 1, 0, 0
	spritePiece	0, -$18, 3, 2, 2, 1, 1, 0, 0
	spritePiece	-$18, -$18, 3, 2, 8, 1, 1, 0, 0
Shield_F_7_End

Shield_F_8:	spriteHeader
	spritePiece	8, -$10, 1, 1, 0, 1, 1, 0, 0
	spritePiece	0, -$18, 3, 1, 1, 1, 1, 0, 0
	spritePiece	-$18, -$18, 3, 2, 4, 1, 1, 0, 0
Shield_F_8_End

Shield_F_9:	spriteHeader
	spritePiece	$C, -$18, 2, 4, 0, 0, 0, 0, 0
	spritePiece	4, 8, 3, 1, 8, 0, 0, 0, 0
	spritePiece	$C, $10, 2, 1, $B, 0, 0, 0, 0
Shield_F_9_End

Shield_F_A:	spriteHeader
	spritePiece	-$14, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	4, -$18, 3, 3, 9, 0, 0, 0, 0
	spritePiece	-$14, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	4, 0, 3, 3, 9, 0, 1, 0, 0
Shield_F_A_End

Shield_F_B:	spriteHeader
	spritePiece	-$1C, -$18, 4, 3, 0, 0, 0, 0, 0
	spritePiece	4, -$18, 3, 3, $C, 0, 0, 0, 0
	spritePiece	-$1C, 0, 4, 3, $15, 0, 1, 0, 0
	spritePiece	4, 0, 3, 3, $C, 0, 1, 0, 0
Shield_F_B_End

Shield_F_C:	spriteHeader
	spritePiece	$C, -8, 2, 4, 0, 0, 1, 0, 0
	spritePiece	4, -$10, 3, 1, 8, 0, 1, 0, 0
	spritePiece	$C, -$18, 2, 1, $B, 0, 1, 0, 0
Shield_F_C_End

Shield_F_D:	spriteHeader
	spritePiece	-$1C, -$18, 4, 3, 0, 0, 0, 0, 0
	spritePiece	4, -$18, 3, 3, $C, 0, 0, 0, 0
	spritePiece	-$1C, 0, 4, 3, 0, 0, 1, 0, 0
	spritePiece	4, 0, 3, 3, $C, 0, 1, 0, 0
Shield_F_D_End

Shield_F_E:	spriteHeader
	spritePiece	-$20, -$18, 4, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 4, 3, $C, 0, 0, 0, 0
	spritePiece	-$20, 0, 4, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 4, 3, $C, 0, 1, 0, 0
Shield_F_E_End

Shield_F_F:	spriteHeader
	spritePiece	-$18, -$18, 3, 2, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 2, 6, 0, 0, 0, 0
Shield_F_F_End

Shield_F_10:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 0, 0, 0, 0
Shield_F_10_End

Shield_F_11:	spriteHeader
	spritePiece	-$18, -$18, 3, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, $C, 0, 0, 0, 0
	spritePiece	8, 0, 1, 1, $15, 0, 0, 0, 0
Shield_F_11_End

Shield_F_12:	spriteHeader
	spritePiece	-$18, -$18, 3, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 4, $C, 0, 0, 0, 0
	spritePiece	8, 8, 2, 1, $18, 0, 0, 0, 0
Shield_F_12_End

Shield_F_13:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 9, 0, 1, 0, 0
Shield_F_13_End

Shield_F_14:	spriteHeader
	spritePiece	0, -8, 3, 4, 0, 1, 1, 0, 0
	spritePiece	-$18, -8, 3, 4, $C, 1, 1, 0, 0
	spritePiece	-$18, -$10, 2, 1, $18, 1, 1, 0, 0
Shield_F_14_End

Shield_F_15:	spriteHeader
	spritePiece	0, -8, 3, 4, 0, 1, 1, 0, 0
	spritePiece	-$18, 0, 3, 3, $C, 1, 1, 0, 0
	spritePiece	-$10, -8, 1, 1, $15, 1, 1, 0, 0
Shield_F_15_End

Shield_F_16:	spriteHeader
	spritePiece	-$18, 0, 3, 3, 0, 1, 1, 0, 0
	spritePiece	0, 0, 3, 3, 9, 1, 1, 0, 0
Shield_F_16_End

Shield_F_17:	spriteHeader
	spritePiece	0, 8, 3, 2, 0, 1, 1, 0, 0
	spritePiece	-$18, 8, 3, 2, 6, 1, 1, 0, 0
Shield_F_17_End

Shield_F_18:	spriteHeader
Shield_F_18_End

	even

