; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
DPLC_LightningShield:	mappingsTable
		mappingsTableEntry.w	Shield_L_DPLC0
		mappingsTableEntry.w	Shield_L_DPLC1
		mappingsTableEntry.w	Shield_L_DPLC2
		mappingsTableEntry.w	Shield_L_DPLC3
		mappingsTableEntry.w	Shield_L_DPLC4
		mappingsTableEntry.w	Shield_L_DPLC5
		mappingsTableEntry.w	Shield_L_DPLC6
		mappingsTableEntry.w	Shield_L_DPLC7
		mappingsTableEntry.w	Shield_L_DPLC8
		mappingsTableEntry.w	Shield_L_DPLC9
		mappingsTableEntry.w	Shield_L_DPLCA
		mappingsTableEntry.w	Shield_L_DPLCB
		mappingsTableEntry.w	Shield_L_DPLCC
		mappingsTableEntry.w	Shield_L_DPLCD
		mappingsTableEntry.w	Shield_L_DPLC0
		mappingsTableEntry.w	Shield_L_DPLC1
		mappingsTableEntry.w	Shield_L_DPLC2
		mappingsTableEntry.w	Shield_L_DPLC3
		mappingsTableEntry.w	Shield_L_DPLC4
		mappingsTableEntry.w	Shield_L_DPLC5
		mappingsTableEntry.w	Shield_L_DPLC6
		mappingsTableEntry.w	Shield_L_DPLC7
		mappingsTableEntry.w	Shield_L_DPLC8

Shield_L_DPLC0:	dplcHeader
	dplcEntry	4, 0
	dplcEntry	8, 4
	dplcEntry	4, $C
Shield_L_DPLC0_End

Shield_L_DPLC1:	dplcHeader
	dplcEntry	9, $10
	dplcEntry	9, $19
Shield_L_DPLC1_End

Shield_L_DPLC2:	dplcHeader
	dplcEntry	3, $22
	dplcEntry	$C, $25
	dplcEntry	3, $31
Shield_L_DPLC2_End

Shield_L_DPLC3:	dplcHeader
	dplcEntry	3, $34
	dplcEntry	$C, $37
	dplcEntry	6, $43
Shield_L_DPLC3_End

Shield_L_DPLC4:	dplcHeader
	dplcEntry	6, $49
	dplcEntry	6, $4F
Shield_L_DPLC4_End

Shield_L_DPLC5:	dplcHeader
	dplcEntry	3, $34
	dplcEntry	$C, $37
	dplcEntry	6, $43
Shield_L_DPLC5_End

Shield_L_DPLC6:	dplcHeader
	dplcEntry	3, $22
	dplcEntry	$C, $25
	dplcEntry	3, $31
Shield_L_DPLC6_End

Shield_L_DPLC7:	dplcHeader
	dplcEntry	9, $10
	dplcEntry	9, $19
Shield_L_DPLC7_End

Shield_L_DPLC8:	dplcHeader
	dplcEntry	4, 0
	dplcEntry	8, 4
	dplcEntry	4, $C
Shield_L_DPLC8_End

Shield_L_DPLC9:	dplcHeader
	dplcEntry	9, $55
	dplcEntry	9, $5E
Shield_L_DPLC9_End

Shield_L_DPLCA:	dplcHeader
	dplcEntry	9, $67
	dplcEntry	9, $70
Shield_L_DPLCA_End

Shield_L_DPLCB:	dplcHeader
	dplcEntry	9, $79
Shield_L_DPLCB_End

Shield_L_DPLCC:	dplcHeader
	dplcEntry	1, $81
Shield_L_DPLCC_End

Shield_L_DPLCD:	dplcHeader
	dplcEntry	4, $81
Shield_L_DPLCD_End

	even
