; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_BubbleShield:	mappingsTable
	mappingsTableEntry.w	Shield_B_0
	mappingsTableEntry.w	Shield_B_1
	mappingsTableEntry.w	Shield_B_2
	mappingsTableEntry.w	Shield_B_3
	mappingsTableEntry.w	Shield_B_4
	mappingsTableEntry.w	Shield_B_5
	mappingsTableEntry.w	Shield_B_6
	mappingsTableEntry.w	Shield_B_7
	mappingsTableEntry.w	Shield_B_8
	mappingsTableEntry.w	Shield_B_9
	mappingsTableEntry.w	Shield_B_A
	mappingsTableEntry.w	Shield_B_B
	mappingsTableEntry.w	Shield_B_C

Shield_B_0:	spriteHeader
	spritePiece	-$10, -$18, 4, 1, 0, 0, 0, 0, 0
Shield_B_0_End

Shield_B_1:	spriteHeader
	spritePiece	-$18, -$18, 3, 2, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 2, 0, 1, 0, 0, 0
Shield_B_1_End

Shield_B_2:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 0, 1, 0, 0, 0
Shield_B_2_End

Shield_B_3:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 0, 1, 0, 0, 0
Shield_B_3_End

Shield_B_4:	spriteHeader
	spritePiece	-$18, -$10, 3, 4, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 3, 4, 0, 1, 0, 0, 0
Shield_B_4_End

Shield_B_5:	spriteHeader
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_B_5_End

Shield_B_6:	spriteHeader
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_B_6_End

Shield_B_7:	spriteHeader
	spritePiece	-$18, 8, 3, 2, 0, 0, 1, 0, 0
	spritePiece	0, 8, 3, 2, 0, 1, 1, 0, 0
Shield_B_7_End

Shield_B_8:	spriteHeader
	spritePiece	-$10, $10, 2, 1, 0, 0, 1, 0, 0
	spritePiece	0, $10, 2, 1, 0, 1, 1, 0, 0
Shield_B_8_End

Shield_B_9:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_B_9_End

Shield_B_A:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_B_A_End

Shield_B_B:	spriteHeader
	spritePiece	-$1C, -$14, 4, 2, 0, 0, 0, 0, 0
	spritePiece	4, -$14, 3, 2, 8, 0, 0, 0, 0
	spritePiece	-$1C, -4, 4, 3, $E, 0, 0, 0, 0
	spritePiece	4, -4, 3, 3, $E, 1, 0, 0, 0
Shield_B_B_End

Shield_B_C:	spriteHeader
	spritePiece	-$24, -$10, 4, 4, 0, 0, 0, 0, 0
	spritePiece	-4, -$10, 1, 4, $10, 0, 0, 0, 0
	spritePiece	4, -$10, 4, 4, $14, 0, 0, 0, 0
Shield_B_C_End

	even

