; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
DPLC_BubbleShield:	mappingsTable
		mappingsTableEntry.w	Shield_B_DPLC0
		mappingsTableEntry.w	Shield_B_DPLC1
		mappingsTableEntry.w	Shield_B_DPLC2
		mappingsTableEntry.w	Shield_B_DPLC3
		mappingsTableEntry.w	Shield_B_DPLC4
		mappingsTableEntry.w	Shield_B_DPLC5
		mappingsTableEntry.w	Shield_B_DPLC6
		mappingsTableEntry.w	Shield_B_DPLC7
		mappingsTableEntry.w	Shield_B_DPLC8
		mappingsTableEntry.w	Shield_B_DPLC9
		mappingsTableEntry.w	Shield_B_DPLCA
		mappingsTableEntry.w	Shield_B_DPLCB
		mappingsTableEntry.w	Shield_B_DPLCC

Shield_B_DPLC0:	dplcHeader
	dplcEntry	4, 0
Shield_B_DPLC0_End

Shield_B_DPLC1:	dplcHeader
	dplcEntry	6, 4
Shield_B_DPLC1_End

Shield_B_DPLC2:	dplcHeader
	dplcEntry	9, $A
Shield_B_DPLC2_End

Shield_B_DPLC3:	dplcHeader
	dplcEntry	9, $13
Shield_B_DPLC3_End

Shield_B_DPLC4:	dplcHeader
	dplcEntry	$C, $1C
Shield_B_DPLC4_End

Shield_B_DPLC5:	dplcHeader
	dplcEntry	9, $13
Shield_B_DPLC5_End

Shield_B_DPLC6:	dplcHeader
	dplcEntry	9, $A
Shield_B_DPLC6_End

Shield_B_DPLC7:	dplcHeader
	dplcEntry	6, 4
Shield_B_DPLC7_End

Shield_B_DPLC8:	dplcHeader
	dplcEntry	2, 0
Shield_B_DPLC8_End

Shield_B_DPLC9:	dplcHeader
	dplcEntry	9, $28
	dplcEntry	9, $31
Shield_B_DPLC9_End

Shield_B_DPLCA:	dplcHeader
	dplcEntry	9, $3A
	dplcEntry	9, $43
Shield_B_DPLCA_End

Shield_B_DPLCB:	dplcHeader
	dplcEntry	8, $4C
	dplcEntry	6, $54
	dplcEntry	$C, $5A
Shield_B_DPLCB_End

Shield_B_DPLCC:	dplcHeader
	dplcEntry	$10, $66
	dplcEntry	4, $76
	dplcEntry	$10, $7A
Shield_B_DPLCC_End

	even
