; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
DPLC_InstaShield:	mappingsTable
		mappingsTableEntry.w	Shield_I_DPLC0
		mappingsTableEntry.w	Shield_I_DPLC0
		mappingsTableEntry.w	Shield_I_DPLC0
		mappingsTableEntry.w	Shield_I_DPLC1
		mappingsTableEntry.w	Shield_I_DPLC1
		mappingsTableEntry.w	Shield_I_DPLC1
		mappingsTableEntry.w	Shield_I_DPLC1
		mappingsTableEntry.w	Shield_I_DPLC1

Shield_I_DPLC0:	dplcHeader
	dplcEntry	$10, 0
	dplcEntry	7, $10
Shield_I_DPLC0_End

Shield_I_DPLC1:	dplcHeader
	dplcEntry	$10, $17
	dplcEntry	$D, $27
Shield_I_DPLC1_End

	even
