; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_InstaShield:	mappingsTable
	mappingsTableEntry.w	Shield_I_0
	mappingsTableEntry.w	Shield_I_1
	mappingsTableEntry.w	Shield_I_2
	mappingsTableEntry.w	Shield_I_3
	mappingsTableEntry.w	Shield_I_4
	mappingsTableEntry.w	Shield_I_5
	mappingsTableEntry.w	Shield_I_Blank
	mappingsTableEntry.w	Shield_I_Blank

Shield_I_0:	spriteHeader
	spritePiece	-$10, -$18, 3, 1, 0, 0, 0, 0, 0
	spritePiece	-8, -$10, 2, 1, 3, 0, 0, 0, 0
	spritePiece	0, -8, 1, 1, 5, 0, 0, 0, 0
Shield_I_0_End

Shield_I_1:	spriteHeader
	spritePiece	8, -$10, 2, 1, 6, 0, 0, 0, 0
	spritePiece	0, -8, 3, 1, 8, 0, 0, 0, 0
	spritePiece	0, 0, 2, 1, $B, 0, 0, 0, 0
Shield_I_1_End

Shield_I_2:	spriteHeader
	spritePiece	0, 0, 3, 2, $D, 0, 0, 0, 0
	spritePiece	-8, $10, 4, 1, $13, 0, 0, 0, 0
Shield_I_2_End

Shield_I_3:	spriteHeader
	spritePiece	-$18, -$10, 4, 1, 0, 0, 0, 0, 0
	spritePiece	-$18, -8, 3, 1, 4, 0, 0, 0, 0
	spritePiece	-$18, 0, 2, 3, 7, 0, 0, 0, 0
Shield_I_3_End

Shield_I_4:	spriteHeader
	spritePiece	-$10, -$18, 2, 1, $D, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 4, $F, 0, 0, 0, 0
	spritePiece	8, 8, 2, 1, $1B, 0, 0, 0, 0
Shield_I_4_End

Shield_I_5:	spriteHeader
	spritePiece	-$18, -$10, 2, 1, $1B, 1, 1, 0, 0
	spritePiece	-$18, -8, 3, 4, $F, 1, 1, 0, 0
	spritePiece	0, $10, 2, 1, $D, 1, 1, 0, 0
Shield_I_5_End

Shield_I_Blank:	spriteHeader
Shield_I_Blank_End

	even

