; ---------------------------------------------------------------------------
; Sonic 1 Sprite Mappings - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this mapping script.
; ---------------------------------------------------------------------------
Map_LightningShield:	mappingsTable
	mappingsTableEntry.w	Shield_L_0
	mappingsTableEntry.w	Shield_L_1
	mappingsTableEntry.w	Shield_L_2
	mappingsTableEntry.w	Shield_L_3
	mappingsTableEntry.w	Shield_L_4
	mappingsTableEntry.w	Shield_L_5
	mappingsTableEntry.w	Shield_L_6
	mappingsTableEntry.w	Shield_L_7
	mappingsTableEntry.w	Shield_L_8
	mappingsTableEntry.w	Shield_L_9
	mappingsTableEntry.w	Shield_L_A
	mappingsTableEntry.w	Shield_L_B
	mappingsTableEntry.w	Shield_L_C
	mappingsTableEntry.w	Shield_L_D
	mappingsTableEntry.w	Shield_L_0
	mappingsTableEntry.w	Shield_L_1
	mappingsTableEntry.w	Shield_L_2
	mappingsTableEntry.w	Shield_L_3
	mappingsTableEntry.w	Shield_L_4
	mappingsTableEntry.w	Shield_L_5
	mappingsTableEntry.w	Shield_L_6
	mappingsTableEntry.w	Shield_L_7
	mappingsTableEntry.w	Shield_L_8
	mappingsTableEntry.w	Shield_L_E

Shield_L_0:	spriteHeader
	spritePiece	-8, -$18, 4, 1, 0, 0, 0, 0, 0
	spritePiece	8, -$10, 2, 4, 4, 0, 0, 0, 0
	spritePiece	-8, $10, 4, 1, $C, 0, 0, 0, 0
Shield_L_0_End

Shield_L_1:	spriteHeader
	spritePiece	0, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, 0, 3, 3, 9, 0, 0, 0, 0
Shield_L_1_End

Shield_L_2:	spriteHeader
	spritePiece	-8, -$18, 3, 1, 0, 0, 0, 0, 0
	spritePiece	0, -$10, 3, 4, 3, 0, 0, 0, 0
	spritePiece	-8, $10, 3, 1, $F, 0, 0, 0, 0
Shield_L_2_End

Shield_L_3:	spriteHeader
	spritePiece	-8, -$18, 3, 1, 0, 0, 0, 0, 0
	spritePiece	-8, -$10, 4, 3, 3, 0, 0, 0, 0
	spritePiece	-8, 8, 3, 2, $F, 0, 0, 0, 0
Shield_L_3_End

Shield_L_4:	spriteHeader
	spritePiece	-8, -$18, 2, 3, 0, 0, 0, 0, 0
	spritePiece	-8, 0, 2, 3, 6, 0, 0, 0, 0
Shield_L_4_End

Shield_L_5:	spriteHeader
	spritePiece	-$10, -$18, 3, 1, 0, 1, 0, 0, 0
	spritePiece	-$18, -$10, 4, 3, 3, 1, 0, 0, 0
	spritePiece	-$10, 8, 3, 2, $F, 1, 0, 0, 0
Shield_L_5_End

Shield_L_6:	spriteHeader
	spritePiece	-$10, -$18, 3, 1, 0, 1, 0, 0, 0
	spritePiece	-$18, -$10, 3, 4, 3, 1, 0, 0, 0
	spritePiece	-$10, $10, 3, 1, $F, 1, 0, 0, 0
Shield_L_6_End

Shield_L_7:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 1, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 9, 1, 0, 0, 0
Shield_L_7_End

Shield_L_8:	spriteHeader
	spritePiece	-$18, -$18, 4, 1, 0, 1, 0, 0, 0
	spritePiece	-$18, -$10, 2, 4, 4, 1, 0, 0, 0
	spritePiece	-$18, $10, 4, 1, $C, 1, 0, 0, 0
Shield_L_8_End

Shield_L_9:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 9, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 1, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_L_9_End

Shield_L_A:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 9, 0, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 9, 1, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_L_A_End

Shield_L_B:	spriteHeader
	spritePiece	-$18, -$18, 3, 3, 0, 0, 0, 0, 0
	spritePiece	0, -$18, 3, 3, 0, 1, 0, 0, 0
	spritePiece	-$18, 0, 3, 3, 0, 0, 1, 0, 0
	spritePiece	0, 0, 3, 3, 0, 1, 1, 0, 0
Shield_L_B_End

Shield_L_C:	spriteHeader
	spritePiece	-4, -4, 1, 1, $15, 0, 0, 0, 0
Shield_L_C_End

Shield_L_D:	spriteHeader
	spritePiece	-8, -8, 2, 2, $16, 0, 0, 0, 0
Shield_L_D_End

Shield_L_E:	spriteHeader
Shield_L_E_End

	even
