; ---------------------------------------------------------------------------
; Sonic 1 Dynamic PLC Script - Generated by Sonic Triad Studio
; To be used with spritePiece Macro. Set SonicMappingsVer to 1 to use this DPLC script.
; ---------------------------------------------------------------------------
DPLC_FlameShield:	mappingsTable
		mappingsTableEntry.w	Shield_F_DPLC0
		mappingsTableEntry.w	Shield_F_DPLC1
		mappingsTableEntry.w	Shield_F_DPLC2
		mappingsTableEntry.w	Shield_F_DPLC3
		mappingsTableEntry.w	Shield_F_DPLC4
		mappingsTableEntry.w	Shield_F_DPLC5
		mappingsTableEntry.w	Shield_F_DPLC6
		mappingsTableEntry.w	Shield_F_DPLC7
		mappingsTableEntry.w	Shield_F_DPLC8
		mappingsTableEntry.w	Shield_F_DPLC9
		mappingsTableEntry.w	Shield_F_DPLCA
		mappingsTableEntry.w	Shield_F_DPLCB
		mappingsTableEntry.w	Shield_F_DPLCC
		mappingsTableEntry.w	Shield_F_DPLCD
		mappingsTableEntry.w	Shield_F_DPLCE
		mappingsTableEntry.w	Shield_F_DPLCF
		mappingsTableEntry.w	Shield_F_DPLC10
		mappingsTableEntry.w	Shield_F_DPLC11
		mappingsTableEntry.w	Shield_F_DPLC12
		mappingsTableEntry.w	Shield_F_DPLC13
		mappingsTableEntry.w	Shield_F_DPLC14
		mappingsTableEntry.w	Shield_F_DPLC15
		mappingsTableEntry.w	Shield_F_DPLC16
		mappingsTableEntry.w	Shield_F_DPLC17
		mappingsTableEntry.w	Shield_F_DPLC18

Shield_F_DPLC0:	dplcHeader
	dplcEntry	1, 0
	dplcEntry	3, 1
	dplcEntry	6, 4
Shield_F_DPLC0_End

Shield_F_DPLC1:	dplcHeader
	dplcEntry	2, $A
	dplcEntry	6, $C
	dplcEntry	6, $12
Shield_F_DPLC1_End

Shield_F_DPLC2:	dplcHeader
	dplcEntry	1, $18
	dplcEntry	9, $19
	dplcEntry	9, $22
Shield_F_DPLC2_End

Shield_F_DPLC3:	dplcHeader
	dplcEntry	3, $2B
	dplcEntry	9, $2E
	dplcEntry	9, $37
Shield_F_DPLC3_End

Shield_F_DPLC4:	dplcHeader
	dplcEntry	6, $40
	dplcEntry	6, $46
Shield_F_DPLC4_End

Shield_F_DPLC5:	dplcHeader
	dplcEntry	3, $2B
	dplcEntry	9, $2E
	dplcEntry	9, $37
Shield_F_DPLC5_End

Shield_F_DPLC6:	dplcHeader
	dplcEntry	1, $18
	dplcEntry	9, $19
	dplcEntry	9, $22
Shield_F_DPLC6_End

Shield_F_DPLC7:	dplcHeader
	dplcEntry	2, $A
	dplcEntry	6, $C
	dplcEntry	6, $12
Shield_F_DPLC7_End

Shield_F_DPLC8:	dplcHeader
	dplcEntry	1, 0
	dplcEntry	3, 1
	dplcEntry	6, 4
Shield_F_DPLC8_End

Shield_F_DPLC9:	dplcHeader
	dplcEntry	8, $4C
	dplcEntry	3, $54
	dplcEntry	2, $57
Shield_F_DPLC9_End

Shield_F_DPLCA:	dplcHeader
	dplcEntry	9, $59
	dplcEntry	9, $62
Shield_F_DPLCA_End

Shield_F_DPLCB:	dplcHeader
	dplcEntry	$C, $6B
	dplcEntry	9, $77
	dplcEntry	$C, $6B
Shield_F_DPLCB_End

Shield_F_DPLCC:	dplcHeader
	dplcEntry	8, $4C
	dplcEntry	3, $54
	dplcEntry	2, $57
Shield_F_DPLCC_End

Shield_F_DPLCD:	dplcHeader
	dplcEntry	$C, $80
	dplcEntry	9, $8C
Shield_F_DPLCD_End

Shield_F_DPLCE:	dplcHeader
	dplcEntry	$C, $95
	dplcEntry	$C, $A1
Shield_F_DPLCE_End

Shield_F_DPLCF:	dplcHeader
	dplcEntry	6, $AD
	dplcEntry	6, $B3
Shield_F_DPLCF_End

Shield_F_DPLC10:	dplcHeader
	dplcEntry	9, $B9
	dplcEntry	9, $C2
Shield_F_DPLC10_End

Shield_F_DPLC11:	dplcHeader
	dplcEntry	$C, $CB
	dplcEntry	9, $D7
	dplcEntry	1, $E0
Shield_F_DPLC11_End

Shield_F_DPLC12:	dplcHeader
	dplcEntry	$C, $E1
	dplcEntry	$C, $ED
	dplcEntry	2, $F9
Shield_F_DPLC12_End

Shield_F_DPLC13:	dplcHeader
	dplcEntry	9, $FB
	dplcEntry	9, $104
Shield_F_DPLC13_End

Shield_F_DPLC14:	dplcHeader
	dplcEntry	$C, $E1
	dplcEntry	$C, $ED
	dplcEntry	2, $F9
Shield_F_DPLC14_End

Shield_F_DPLC15:	dplcHeader
	dplcEntry	$C, $CB
	dplcEntry	9, $D7
	dplcEntry	1, $E0
Shield_F_DPLC15_End

Shield_F_DPLC16:	dplcHeader
	dplcEntry	9, $C2
	dplcEntry	9, $B9
Shield_F_DPLC16_End

Shield_F_DPLC17:	dplcHeader
	dplcEntry	6, $AD
	dplcEntry	6, $B3
Shield_F_DPLC17_End

Shield_F_DPLC18:	dplcHeader
Shield_F_DPLC18_End

	even
