; Compiled as a blob
	binclude	"palette/S2 Level Select/GHZ.bin"
	binclude	"palette/S2 Level Select/LZ.bin"
	binclude	"palette/S2 Level Select/MZ.bin"
	binclude	"palette/S2 Level Select/SLZ.bin"
	binclude	"palette/S2 Level Select/SYZ.bin"
	binclude	"palette/S2 Level Select/SBZ1.bin"
	binclude	"palette/S2 Level Select/SBZ2.bin"
	binclude	"palette/S2 Level Select/SBZ3.bin"
	binclude	"palette/S2 Level Select/FZ.bin"
	binclude	"palette/S2 Level Select/Special.bin"
	binclude	"palette/S2 Level Select/Sound Sonic.bin"